#!/usr/bin/env python3
"""Validate and merge official metadata with the Thai presentation copy."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
SOURCE_PATH = DATA_DIR / "source-usecases.json"
TRANSLATION_PATHS = [DATA_DIR / f"usecases-th-{part}.json" for part in ("01", "02", "03")]
OUTPUT_PATH = DATA_DIR / "usecases-data.js"
CATEGORIES = {
    "งานประจำ",
    "ข้อมูลและการตัดสินใจ",
    "การเงินและกลยุทธ์",
    "การขายและปฏิบัติการ",
    "การศึกษาและอาชีพ",
    "ออกแบบและสร้าง",
    "วิศวกรรมซอฟต์แวร์",
    "วิทยาศาสตร์และความปลอดภัย",
}
TRANSLATION_KEYS = {
    "index",
    "slug",
    "titleTh",
    "titleEn",
    "summaryTh",
    "categoryTh",
    "workflow",
    "promptTh",
    "checkTh",
}


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def validate_translation(item: dict, source: dict) -> None:
    index = item.get("index")
    if set(item) != TRANSLATION_KEYS:
        raise ValueError(f"Index {index}: translation keys do not match the deck schema")
    if item["slug"] != source["slug"] or item["titleEn"] != source["title"]:
        raise ValueError(f"Index {index}: source identity mismatch")
    if item["categoryTh"] not in CATEGORIES:
        raise ValueError(f"Index {index}: unsupported category {item['categoryTh']}")
    if len(item["workflow"]) != 4:
        raise ValueError(f"Index {index}: workflow must contain exactly four steps")
    for step in item["workflow"]:
        if set(step) != {"label", "detail"} or not step["label"] or not step["detail"]:
            raise ValueError(f"Index {index}: invalid workflow step")
    for key in ("titleTh", "summaryTh", "promptTh", "checkTh"):
        if not isinstance(item[key], str) or not item[key].strip():
            raise ValueError(f"Index {index}: missing {key}")


def main() -> None:
    source_payload = load_json(SOURCE_PATH)
    source_items = source_payload["useCases"]
    translations = []
    for path in TRANSLATION_PATHS:
        translations.extend(load_json(path))

    translations.sort(key=lambda item: item["index"])
    if len(source_items) != 99 or len(translations) != 99:
        raise ValueError(f"Expected 99 source and translation records, got {len(source_items)} and {len(translations)}")
    if [item["index"] for item in translations] != list(range(99)):
        raise ValueError("Translation indices must be contiguous from 0 through 98")

    merged = []
    for source, translation in zip(source_items, translations, strict=True):
        if source["index"] != translation["index"]:
            raise ValueError(f"Index order mismatch at {translation['index']}")
        validate_translation(translation, source)
        merged.append(
            {
                **translation,
                "difficulty": source["difficulty"],
                "time": source["time"],
                "tags": source["tags"],
                "image": source["image"],
                "url": source["url"],
            }
        )

    serialized = json.dumps(merged, ensure_ascii=False, separators=(",", ":"))
    banner = (
        "// Generated by scripts/build_deck_data.py from official OpenAI source metadata "
        "and reviewed Thai presentation copy.\n"
    )
    OUTPUT_PATH.write_text(f"{banner}window.USE_CASES={serialized};\n", encoding="utf-8")
    print(f"Built {len(merged)} slides in {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
